services:
  pft:
    image: akaririn/personal-finance-tracker:latest
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mysql
    environment:
      SERVER_PORT: "8000"
      DB_URL: "mysql://mysql:3306/pft"
      DB_USERNAME: "root"
      DB_PASSWORD: "1234"
      JWT_SECRET: "YOUR_JWT_SECRET"
  mysql:
    image: mysql:latest
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "pft"
      MYSQL_USER: "pft"
      MYSQL_PASSWORD: "pft_password"